version: "3.5"
services:
  
  redis:
    image: redis:alpine3.13
    container_name: redis
    restart: always
    ports:
        - "6379"
    networks:
        - phish_net
  
  rspamd:
    image: 6point6/rspamd:0.1
    container_name: rspamd
    volumes:
      - ./rspamd/lib/dkim:/var/lib/rspamd/dkim
    env_file:
      - 'settings.env'
    depends_on:
      - redis
    networks:
      - phish_net

networks:
  phish_net:
    name: phish_net